### PR TITLE
[DO-14] Updates to allow for EIP use.

### PR DESCRIPTION
**Pull request by sapiensantiquus**

### CODE REVIEW

**Comment by sapiensantiquus** [comment]
@simplyadrian @notyost This seems to work, even if not perfect.

**Comment by notyost** [comment]
seems logical to me -- i wonder is the other behavior useful in certain situations  aka should it be a conditional thing? or otherwise working ftw 👍

**Comment by simplyadrian** [comment]
FTW!

**Comment by simplyadrian** [comment]
Im going to merge this ...

**Comment by sapiensantiquus** [comment]
@notyost It defaults to the original functionality in the case that EIPs are not defined. Or did you mean something else?

**Comment by notyost** [comment]
i meant just as far as being able to provide a valid ip list only -- without ddb

**Pull request merged**
